export const foodItems = [
  {
    id: 1,
    name: 'Biryani (Chicken)',
    image: 'Assets/Images/1.jpg',
    price: 300,
    serving: 1,
    availableOnDay: 0,
  },
  {
    id: 2,
    name: 'Karahi (Chicken)',
    image: 'Assets/Images/2.jpg',
    price: 1000,
    serving: 4,
    availableOnDay: 1,
  },
  {
    id: 3,
    name: 'Handi (Chicken)',
    image: 'Assets/Images/3.jpg',
    price: 1000,
    serving: 4,
    availableOnDay: 2,
  },
  {
    id: 4,
    name: 'Jalfrezi (Chicken)',
    image: 'Assets/Images/4.jpg',
    price: 700,
    serving: 2,
    availableOnDay: 3,
  },
  {
    id: 5,
    name: 'Daal (Moong)',
    image: 'Assets/Images/5.jpg',
    price: 200,
    serving: 2,
    availableOnDay: 4,
  },
  {
    id: 6,
    name: 'Nihari (Chicken)',
    image: 'Assets/Images/6.jpg',
    price: 1200,
    serving: 4,
    availableOnDay: 5,
  },
  {
    id: 7,
    name: 'Spicy Tawa Qeema (Mutton)',
    image: 'Assets/Images/7.jpg',
    price: 1500,
    serving: 4,
    availableOnDay: 6,
  },
  {
    id: 8,
    name: 'Hyderabadi Haleem',
    image: 'Assets/Images/8.jpg',
    price: 1000,
    serving: 2,
    availableOnDay: 7,
  },
  {
    id: 9,
    name: 'Fruit Chaat',
    image: 'Assets/Images/9.jpg',
    price: 100,
    serving: 1,
    availableOnDay: 0,
  },
];
